name: Generate SBOM Report with Syft

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  generate-sbom:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Syft
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Generate SBOM
      run: |
        syft docker.io/kodekloud/webapp-color:latest -o spdx-xml > sbom.xml  # 포맷을 spdx-xml로 변경, 파일 이름도 sbom.xml로 맞춤

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: sbom-report
        path: sbom.xml  # 이제 sbom.xml 파일이 생성됐으니 이 경로로 업로드 가능
